name = "MatterEnv"
uuid = "9a24efd3-56f5-4b6c-a4cc-8c3068a60637"
authors = ["Yaozhenghang Ma <yaozhenghang.ma@gmail.com> and contributors"]
version = "0.1.2"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
